
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;


public class sym {
  
	// Keywords [1 - 19]
	public static final int PROG = 1;
	public static final int READ = 2;
	public static final int PRINT = 3;
	public static final int NEW = 4;
	public static final int	IF = 5;
	public static final int ELSE = 6;
	public static final int MAP = 7;
	public static final int BREAK = 8;
	public static final int CONTINUE = 9;
	public static final int RETURN = 10;
	public static final int DO = 11;
	public static final int WHILE = 12;
	public static final int UNION = 13;
	public static final int VOID = 14;
	public static final int CLASS = 15;
	public static final int EXTENDS = 16;
	
	// Operators [20 - 49]
	public static final int PLUS = 20;
	public static final int DOUBLEPLUS = 21;
	public static final int MINUS = 22;
	public static final int DOUBLEMINUS = 23;
	public static final int MUL = 24;
	public static final int DIV = 25;
	public static final int MOD = 26;
	public static final int SEMI = 27;
	public static final int LPAREN = 28;
	public static final int RPAREN = 29;
	public static final int LBRACKET = 30;
	public static final int RBRACKET = 31;
	public static final int LBRACE = 32;
	public static final int RBRACE = 33;
	public static final int AND = 34;
	public static final int OR = 35;
	public static final int EQUAL = 36;    
	public static final int NOTEQUAL = 37;
	public static final int LESSEQUAL = 38;
	public static final int GREATEQUAL = 39;
	public static final int GREAT = 40;
	public static final int LESS = 41;
	public static final int COMMA = 42;
	public static final int DOUBLEEQUAL = 43;
	
	// Identifiers [50 - 59]
	public static final int IDENT = 50;
	
	// Constants [60 - 69]
	public static final int CONSTNUMBER = 60;
	public static final int CONSTCHAR = 61;
	public static final int CONSTBOOLEAN = 62;
	
	// Other [70 - 79 + 0]
	public static final int EOF = 0;
	public static final int error = 70;
	
  
}

