
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 24 15:36:36 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 17;
  public static final int READ = 5;
  public static final int IDENT = 29;
  public static final int PLUS = 16;
  public static final int RPAREN = 25;
  public static final int RBRACE = 21;
  public static final int EQUAL = 12;
  public static final int CONSTNUMBER = 26;
  public static final int SEMI = 9;
  public static final int RETURN = 8;
  public static final int LPAREN = 24;
  public static final int LBRACKET = 22;
  public static final int LBRACE = 20;
  public static final int DOUBLEPLUS = 13;
  public static final int CONSTBOOLEAN = 27;
  public static final int RBRACKET = 23;
  public static final int COMMA = 10;
  public static final int EOF = 0;
  public static final int DIV = 18;
  public static final int PROG = 2;
  public static final int DOUBLEMINUS = 14;
  public static final int UNION = 11;
  public static final int CONSTCHAR = 28;
  public static final int MINUS = 15;
  public static final int CONST = 7;
  public static final int PRINT = 4;
  public static final int error = 1;
  public static final int NEW = 6;
  public static final int MUL = 19;
  public static final int VOID = 3;
}

